name: taxcalc-dev
channels:
  - conda-forge
dependencies:
- "python>=3.9, <3.12"
- "numpy>=1.20"
- "pandas>=2.0"
- "bokeh>=1.4, <3.0"
- "paramtools>=0.18.0"
- numba
- curl
- pytest
- pytest-xdist
- pycodestyle
- pylint
- coverage
- behresp
- openpyxl
- pip
- pip:
    - jupyter-book
